linux:
  image: python:3.8
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  script:
    - curl -sSL https://get.docker.com/ | sh
    - python -m pip install -r requirements-dev.txt
    - python ./bin/run_tests.py

windows:
  tags:
    - shared-windows
    - windows
    - windows-1809
  variables:
    - PYTHON=C:\\Python36\\python
  script:
    - choco install python3 --version 3.6.8 --no-progress -y
    - $PYTHON -m pip install -r requirements-dev.txt
    - $PYTHON ./bin/run_tests.py
