language: generic

matrix:
  include:
    # Linux Python 3
    - sudo: required
      language: python
      python: 3.5
      services: docker
      env: PYTHON=python

    # Linux Python 3
    - sudo: required
      language: python
      python: 3.5
      services: docker
      arch: arm64
      env: PYTHON=python

    # Linux Python 3
    - sudo: required
      language: python
      python: 3.5
      services: docker
      arch: ppc64le
      env: PYTHON=python

    # Linux Python 3
    - sudo: required
      language: python
      python: 3.5
      services: docker
      arch: s390x
      env: PYTHON=python

    # macOS Python 3
    - os: osx
      env: PYTHON=python3

    - os: windows
      language: shell
      before_install:
       - choco install python3 --version 3.5.4 --no-progress -y
      install:
       - C:\\Python35\\python -m pip install -r requirements-dev.txt
      script:
       - C:\\Python35\\python ./bin/run_tests.py

install: $PYTHON -m pip install -r requirements-dev.txt

script: $PYTHON ./bin/run_tests.py
