matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip install .
      python ./run_tests.py
    else
      # linux test requires root to clean up the wheelhouse (docker runs as root)
      sudo pip install .
      sudo python ./run_tests.py
    fi
