site_name: cibuildwheel
docs_dir: docs
theme: readthedocs
repo_url: https://github.com/joerick/cibuildwheel

nav:
  - Home: index.md
  - "Setup guide": setup.md
  - "Options": options.md
  - deliver-to-pypi.md
  - faq.md
  - contributing.md
markdown_extensions:
  - fenced_code
  - toc:
      permalink: True
  - attr_list
  - admonition
