version: 2

jobs:
  flake8:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - run:
          name: Install flake8
          command: sudo python -m pip install flake8
      - run:
          name: Test.
          command: flake8 --exclude=.git,.venv,site .

  osx-python3.6:
    macos:
      xcode: "9.4.1"
    environment:
      PYTHON: python3
    steps:
      - checkout

      - run:
          name: Prepare the environment.
          command: bash .circleci/prepare.sh
      - run:
          name: Test.
          command: venv/bin/python ./bin/run_tests.py

  osx-python3.7:
    macos:
      xcode: "10.0.0"
    environment:
      PYTHON: python3
    steps:
      - checkout

      - run:
          name: Prepare the environment.
          command: bash .circleci/prepare.sh
      - run:
          name: Test.
          command: venv/bin/python ./bin/run_tests.py

  linux-python3.6:
    docker:
      - image: circleci/python:3.6
    environment:
      PYTHON: python3
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Prepare the environment.
          command: bash .circleci/prepare.sh
      - run:
          name: Test.
          command: venv/bin/python ./bin/run_tests.py

workflows:
  version: 2
  all-tests:
    jobs:
      - flake8
      - osx-python3.6
      - osx-python3.7
      - linux-python3.6
