name: Sample build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels [${{ matrix.result }}]
    runs-on: ubuntu-18.04
    continue-on-error: ${{ matrix.allow_fail }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - result: success
            allow_fail: false
          - result: failure
            allow_fail: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements-dev.txt

      - name: Generate sample project
        run: |
          python -m test.test_projects test.test_0_basic.basic_project sample_project

      - name: Build wheels
        if: matrix.result == 'success'
        run: |
          cd sample_project
          python -m cibuildwheel --output-dir wheelhouse

      - name: Build wheels [expected failure]
        if: matrix.result == 'failure'
        run: |
          cd sample_project
          # sabotage the project to cause an error
          echo '>' >> setup.py
          python -m cibuildwheel --output-dir wheelhouse
