name: Test

on:
  push: {}
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    # skip branch builds on joerick/cibuildwheel, but always build `master` and pull requests
    if: github.repository != 'joerick/cibuildwheel' || github.ref == 'refs/heads/master' || github.event_name == 'pull_request'

    name: Test cibuildwheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        python_version: ['3.7']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      name: Install Python ${{ matrix.python_version }}
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install -r requirements-dev.txt
    - name: Install Visual C++ for Python 2.7
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install vcpython27 -f -y
    - name: Test cibuildwheel
      run: |
        python ./bin/run_tests.py
